### ISSUE TITLE
Move plot creation and movie creation to a different class

### ISSUE THREAD

**Issue by hejtmy** [jirilukavsky/motbox#3]
When track gets imported in psychopy it seems to crash because of missing dependencies in the moviepy etc.

New class which would create these videos etc. but would NOT get imported in psychopy would solve this

**Comment by jirilukavsky** [comment]
Currently I am considering splitting the code and focus mainly on the presentation+psychopy part. The generation and video preview might be better served via [motrack R package](https://github.com/jirilukavsky/motrack).

**Comment by hejtmy** [comment]
I see :)
